baseURL = "https://atreezilla.com"
languageCode = "ru-ru"
title = "atreezilla.com"
theme = "mainroad"
publishDir = "docs"

disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Elkrot"
  bio = "Elcrot and Co"
  #avatar = "img/avatar.png"

[Params]
  subtitle = "" 
  description = "In progress"
  copyright = "Elcrot" 
  opengraph = true 
  schema = true 
  twitter_cards = false 
  readmore = false 
  authorbox = true 
  toc = true 
  pager = true 
  post_meta = ["author", "date", "categories", "translations"] 
  mainSections = ["post", "blog", "news"] 
  dateformat = "2006-01-02" 
  mathjax = true 
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" 
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" 
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] 
  customJS = ["js/custom.js"] 

[Params.style.vars]
  highlightColor = "#e22d30" 


  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  #image = "img/placeholder.png" 
  title = "Mainroad" 
  subtitle = "Subbbbb" 

[Params.sidebar]
  home = "right" 
  list = "left"  
  single = false 

  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  #twitter = "username"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  email = "atreezilla@gmail.com"

# Custom social links
[[Params.widgets.social.custom]]
  #title = "Youtube"
  #url = "https://youtube.com/user/username"
  #icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

[[Params.widgets.social.custom]]
  title = "My Home Page"
  url = "http://example.com"