baseURL = "https://atreezilla.com"
languageCode = "ru-ru"
title = "atreezilla.com"
theme = "jane"
publishDir = "docs"

[[menu.main]]             # config your menu              # 配置目录
  name = "This is Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "external-link"
  weight = 50
  url = "https://gohugo.io"