relativeURLs = true
uglyURLs = true
baseURL = "https://atreezilla.com"
languageCode = "ru-ru"
title = "atreezilla"
theme = "mini"
publishDir = "docs"
ignoreErrors = ["error-remote-getjson"]
disqusShortname = "atreezilla"
googleAnalytics = "266950395"
[params]
  description = "На сайте будет размещена информация о программировании на C#, python , 3D, рисовании, музыке и других интересных вещах"
  enableComments = true
  enableGoogleAnalytics = true