relativeURLs = true
uglyURLs = true
baseURL = "https://atreezilla.com"
languageCode = "ru-ru"
title = "atreezilla"
theme = "mini"
publishDir = "docs"
ignoreErrors = ["error-remote-getjson"]
disqusShortname = "atreezillacom"
googleAnalytics = "266950395"
[params]
  enableComments = true
  enableGoogleAnalytics = true