name: githubp

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4
        
      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.79.0'

      - name: Build
        run: HUGO_ENV="production" hugo --minify

      - name: Deploy
        uses: peaceiris/actions-github-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: ghub-pages
          publish_dir: ./docs
