name: githubp

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4
        
      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.78.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-github-pages@v3.7.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          external_repository:  atreezillacom/atreezillacom.github.io 
          publish_dir: ./docs
